More "service" renames.

diff --git a/src/main-lactoserv/bin/run-under-systemd b/src/main-lactoserv/bin/run-under-systemd
--- a/src/main-lactoserv/bin/run-under-systemd
+++ b/src/main-lactoserv/bin/run-under-systemd
@@ -35,7 +35,7 @@ command=''
 serviceName=''
 
 # Arguments to pass through when starting the system.
-serverArgs=()
+systemArgs=()
 
 while (( $# != 0 )); do
     case "$1" in
@@ -70,13 +70,13 @@ shift
 
 if [[ ${command} =~ ^(run-foreground|start)$ ]]; then
     if (( $# == 0 )); then
-        echo 1>&2 'Server arguments required when starting service.'
+        echo 1>&2 'Service arguments required when starting service.'
         usage
     fi
-    serverArgs=("$@")
+    systemArgs=("$@")
 else
     if (( $# != 0 )); then
-        echo 1>&2 'Server arguments not allowed when manipulating a running service.'
+        echo 1>&2 'Service arguments not allowed when manipulating a running service.'
         usage
     fi
 fi
@@ -93,12 +93,12 @@ fi
 
 # Runs the system in the foreground.
 function do-run-foreground {
-    exec "${runCmd}" --log-to-stdout "${serverArgs[@]}"
+    exec "${runCmd}" --log-to-stdout "${systemArgs[@]}"
 }
 
 # Starts the system, daemon-style.
 function do-start {
-    local fullCommand=("${runCmd}" --print-node-command "${serverArgs[@]}")
+    local fullCommand=("${runCmd}" --print-node-command "${systemArgs[@]}")
 
     # Write the command about to be executed to the log. Note: In a typical OS
     # configuration, the service-specific log can be seen with `journalctl
