Adjust to the exit code thing.

diff --git a/scripts/example-tool b/scripts/example-tool
--- a/scripts/example-tool
+++ b/scripts/example-tool
@@ -15,9 +15,7 @@
 #
 
 function usage {
-    print-usage $'
-    Usage:
-
+    lib helpy print-usage $'
     ${name} <subcommand> ... [<opt> ...] [--] [<arg> ...]
       Does something exemplar. <opt>s and <arg>s depend on the specific
       subcommand.
@@ -43,5 +41,12 @@ process-args "$@" || usage "$?"
 #
 
 # You can list any number of sub-library names in place of `example` below.
-lib --libs=example "$@" \
-|| usage "$?"
+lib --libs=example --quiet "${cmdName}" "${args[@]}"
+exitCode="$?"
+
+if (( exitCode == 127 )); then
+    error-msg "Command not found: ${cmdName}"
+    exit 1
+fi
+
+exit "${exitCode}"
diff --git a/scripts/ubik b/scripts/ubik
--- a/scripts/ubik
+++ b/scripts/ubik
@@ -16,10 +16,8 @@
 #
 
 function usage {
-    print-usage $'
-    Usage:
-
-    ${name} <subcommand> ... [<opt> ...] [--] [<arg> ...]
+    lib helpy print-usage $'
+    ${name} <command> [<subcommand> ...] [<opt> ...] [--] [<arg> ...]
       Run a subcommand. <opt>s and <arg>s depend on the specific subcommand.
 
     ${name} [--help | -h]
@@ -32,6 +30,9 @@ function usage {
 # Want help?
 opt-action --call='{ usage }' help/h
 
+# The main command.
+positional-arg --required --var=cmdName command
+
 # The actual command arguments.
 rest-arg --var=args args
 
@@ -42,5 +43,12 @@ process-args "$@" || usage "$?"
 # Main script
 #
 
-lib "$@" \
-|| usage "$?"
+lib --quiet "${cmdName}" "${args[@]}"
+exitCode="$?"
+
+if (( exitCode == 127 )); then
+    error-msg "Command not found: ${cmdName}"
+    exit 1
+fi
+
+exit "${exitCode}"
