Updates from upstream.

diff --git a/scripts/lib/bashy-node/node-project/find-module-dependencies b/scripts/lib/bashy-node/node-project/find-module-dependencies
--- a/scripts/lib/bashy-node/node-project/find-module-dependencies
+++ b/scripts/lib/bashy-node/node-project/find-module-dependencies
@@ -14,8 +14,8 @@ define-usage $'
     ${name} [<opt> ...] [--] <module-name>
 
     Transitively finds all module dependencies from the one given, which must
-    be the name of a module defined in this codebase. Prints out a JSON object
-    with bindings as follows:
+    be the name of a module defined under the indicated modules directory.
+    Prints out a JSON object with bindings as follows:
 
     * `main: string` -- The originally requested module.
     * `localDeps: [name, ...]` -- Local module dependencies.
@@ -27,10 +27,17 @@ define-usage $'
     If a dependency cycle is detected, this prints a diagnostic message and
     exits with an error.
 
+    This tool is opinionated: The modules directories are taken to define
+    submodules (in the Node sense) under the top-level name `@this`.
+
+    **Note:** Exactly one of the two `--modules-*` options must be specified.
+
     --modules-dir=<dir>
-      Directory containing all source modules. Required. **Note:** Each of the
-      modules is expected to be defined to have the name `@this/<name>` where
-      <name> names the directory the module is in.
+      Path to a directory containing all module sources to be used.
+    --modules-dirs=<json>
+      JSON array of one or more paths to directories containing module sources.
+      If the same-named module exists in more than one modules directory, the
+      first one listed "wins."
 
     ${help}
 '
@@ -38,8 +45,10 @@ define-usage $'
 # Want help?
 opt-action --call='{ usage; exit }' help/h
 
-# Directory containing all the modules
-opt-value --required --var=modulesDir --filter='/./' modules-dir
+# Directory or directories containing all the modules.
+opt-value --var=modulesDir --filter='/./' modules-dir
+opt-value --var=modulesDirsJson --filter='/^\[.*\]$/' modules-dirs
+require-exactly-one-arg-of modules-dir modules-dirs
 
 # The module to start at.
 positional-arg --required --var=moduleName module-name
@@ -51,9 +60,16 @@ process-args "$@" || usage --short
 # Main script
 #
 
-if [[ ! (-d ${modulesDir} && -r ${modulesDir}) ]]; then
-    error-msg "Not a readable directory: ${modulesDir}"
-    exit 1
+modulesDirs=()
+if [[ ${modulesDir} != '' ]]; then
+    if [[ ! (-d ${modulesDir} && -r ${modulesDir}) ]]; then
+        error-msg "Not a readable directory: ${modulesDir}"
+        exit 1
+    fi
+    modulesDirs=("${modulesDir}")
+else
+    jbash-array --raw modulesDirs "${modulesDirsJson}" \
+    || exit "$?"
 fi
 
 # Collect all of the modules referenced by this package, transitively including
@@ -79,11 +95,21 @@ while true; do
 
     # Reminder: `${var##*/}` removes everything up to the last slash. In this
     # case, it's trimming `@this/` off of `oneDep`.
-    moduleDir="${modulesDir}/${oneDep##*/}"
-    pkgFile="${moduleDir}/package.json"
+    oneDepName="${oneDep##*/}"
 
-    if [[ ! -r "${pkgFile}" ]]; then
-        echo "Not readable: ${pkgFile}" 1>&2
+    for moduleDir in "${modulesDirs[@]}"; do
+        moduleDir="${moduleDir}/${oneDepName}"
+        pkgFile="${moduleDir}/package.json"
+
+        if [[ -r ${pkgFile} ]]; then
+            break
+        fi
+
+        moduleDir=''
+    done
+
+    if [[ ${moduleDir} == '' ]]; then
+        error-msg "Could not find module: ${oneDep}"
         exit 1
     fi
 
